### ISSUE TITLE
Automatically create config file when it doesn't exist

### ISSUE THREAD

**Issue by clinch** [nablaa/ds18x20-rest#1]
I'd like to implement a feature to make the config a bit more idiot-proof. 
- Get rid of the default config file and then prompt the user for config values at startup (can even look for existing temperature probes).

**Comment by nablaa** [comment]
Sounds like a good idea! If a config file exists, the program would use that, otherwise it would automatically generate config file stub populated with found temperature sensors, and the user could be prompted for the sensor names.

Please go ahead and implement this feature.
